### fetch all investors 
GET {{baseUrl}}/investor/accounts
Authorization: Bearer {{adminToken}}

### delete all investors 
DELETE {{baseUrl}}/investor/accounts
Authorization: Bearer {{adminToken}}

###
GET http://localhost:4000/api/investor/accounts/account/626128b82fac87bd28bc9659/verify

### 
POST {{baseUrl}}/investor/accounts/account 
Content-Type: application/json

{
    "email": "icheka@getvest.app",
    "password": "password"
}

###
GET http://localhost:4000/api/rounds
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###
POST http://localhost:4000/api/investments
Content-Type: application/json
Authorization: Bearer {{investorToken}}

{
    "roundId": "625918e186fa2b7e809e8ecf",
    "amount": 100,
    "currency": "NGN",
    "transactionRef": "1234"
}

###
GET http://localhost:4000/api/data/currency-rates